### Get all users
GET http://localhost:3000/api/users
Content-Type: application/json

###

### Create a new user
POST http://localhost:3000/api/users
Content-Type: application/json

{
  "username": "newuser",
  "email": "newuser@example.com",
  "password": "password123"
}

###

### Update a user
PATCH http://localhost:3000/api/users
Content-Type: application/json

{
  "userId": "60d0fe4f5311236168a109ca",
  "newUsername": "updateduser"
}

###

### Delete a user
DELETE http://localhost:3000/api/users?userId=60d0fe4f5311236168a109ca
Content-Type: application/json

